### ISSUE TITLE
ProcessExecutor can't run command from working directory

### ISSUE THREAD

**Issue by pgorbachev** [platformlib/platformlib-process#1]
Execution of the following snippet fails with 
```
LocalProcessBuilderFactory 
                            .newLocalProcessBuilder()
/* some configuration omitted */
                            .workDirectory(sdkManagerPath)
                            .commandAndArguments("sdkmanager");
```
fails with following error

>  java.io.IOException: CreateProcess error=2, The system cannot find the file specified
> at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_321]
> at java.lang.ProcessImpl.<init>(ProcessImpl.java:453) ~[?:1.8.0_321]
> at java.lang.ProcessImpl.start(ProcessImpl.java:140) ~[?:1.8.0_321]
> at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_321]

If you specify full path to command in **commandAndArguments** then everything command is executed correctly

**Comment by vicspbsky** [comment]
@pgorbachev, what is operation system?

**Comment by pgorbachev** [comment]
@vicspbsky , If i'am not mistaken it occured on local environment in Windows
